#!/bin/bash

_create_project_vimrc()
{
    if [[ -e ./.vimrc ]]; then
        return
    fi

    command cat > ./.vimrc <<EOL
" PATH "
set path=\$PWD
set path+=/usr/include
$(find ./ \! -name '.*' -mindepth 1 -type d -printf 'set path+="%P"\n')

" CSCOPE "
cscope add /usr/include /usr/include
$(find ./ -name 'cscope.out' -type f -printf 'cscope add "%h" "%h"\n')

" BUILD "
" compiler msbuild
" set makeprg=./build.sh
EOL

    command cscope -Rqbk
    command ctags -R
}

_create_project_vimrc
