#!/bin/bash

_extract()
{
    if [[ $# == 0 ]]; then
        echo "$0 <files...>"
        return
    fi

    while [[ $# != 0 ]]; do

        case "$1" in
            .deb)
                dpkg -x "$1" . ;;
            *.rpm)
                rpm2cpio "$1" | cpio -idmv ;;
            *.tar)
                tar xvf "$1" ;;
            *.tar.gz)
                tar xvzf "$1" ;;
            *.tgz)
                tar xvzf "$1" ;;
            *.tar.bz2)
                tar xvjf "$1" ;;
            *.tbz2)
                tar xvjf "$1" ;;
            *.tar.xz)
                tar xvJf "$1" ;;
            *.txz)
                tar xvJf "$1" ;;
            *.bz2)
                bunzip2 "$1" ;;
            *.rar)
                rar x "$1" ;;
            *.gz)
                gunzip "$1" ;;
            *.zip)
                unzip "$1" ;;
            *.jar)
                unzip "$1" ;;
            *.Z)
                uncompress "$1" ;;
            *.7z)
                7z x "$1" ;;
            *.xz)
                unxz "$1" ;;
            *.a)
                ar x "$1" ;;
            *)
                echo "don't know how to extract '$1'..."  ;;
        esac

        shift
    done
}

_extract "$@"
