#!/bin/bash

_extract()
{
    if [[ $# == 0 ]]; then
        echo "invalid argument count"
        return
    fi

    while [[ $# != 0 ]]; do

        if [[ ! -f $1 ]] ; then
            echo "file '$1' not found"
            shift
            continue
        fi

        case $1 in
            *.tar.bz2)  tar         xvjf    $1    ;;
            *.tar.gz)   tar         xvzf    $1    ;;
            *.bz2)      bunzip2     $1      ;;
            *.rar)      rar         x       $1    ;;
            *.gz)       gunzip      $1      ;;
            *.tar)      tar         xvf     $1    ;;
            *.tbz2)     tar         xvjf    $1    ;;
            *.tgz)      tar         xvzf    $1    ;;
            *.zip)      unzip       $1      ;;
            *.jar)      unzip       $1      ;;
            *.Z)        uncompress  $1      ;;
            *.7z)       7z          x       $1    ;;
            *.xz)       unxz        $1      ;;
            *)          echo "don't know how to extract '$1'..."  ;;
        esac

        shift
    done
}

_extract "$@"
