#!/bin/bash

_http_auth_server()
{
    local PORT=80
    if [ $# -ge 1 ]; then
        PORT=$1
    fi
    python -c "
import SocketServer
from SimpleHTTPServer import SimpleHTTPRequestHandler
class Handler(SimpleHTTPRequestHandler):
    def do_AUTHHEAD(self):
        self.send_response(401)
        self.send_header('WWW-Authenticate', 'Basic realm=\"Test\"')
        self.send_header('Content-type', 'text/html')
        self.end_headers()
    def do_GET(self):
        if self.headers.getheader('Authorization') is None:
            self.do_AUTHHEAD()
        else:
            SimpleHTTPRequestHandler.do_GET(self)
SocketServer.TCPServer(('', ${PORT}), Handler).serve_forever()
"
}

_http_auth_server() "$@"
