#!/bin/bash

_squeeze()
{
    if [[ $# != 2 ]]; then
        echo "$0 <compressed> <uncompressed>"
        return
    fi

    case "$1" in
        *.zip)
            zip "$1" "$2" ;;
        *.jar)
            zip "$1" "$2" ;;
        *.rar)
            rar "$1" "$2" ;;
        *.7z)
            7z a "$1" "$2" ;;
        *.Z)
            compress -cf "$2" > "$1" ;;
        *.bz2)
            bzip2 -c "$2" > "$1" ;;
        *.gz)
            gzip -c "$2" > "$1" ;;
        *.xz)
            xz -c "$2" > "$1" ;;
        *)
            echo "Filetype not recognized" ;;
    esac
}

_squeeze "$@"
